# --------------------------------------------- #
# Note: this file originates in template-docker #
# --------------------------------------------- #

version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/Toronto

  - package-ecosystem: docker
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/Toronto
